[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "wipe", "--transition-fps", "60" ]
set = true

[config.custom_colors]
background_custom = { color = "#0e1514", blend = false }

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

# Swaync
[templates.swaync]
input_path = './templates/swaync.css'
output_path = '~/.config/swaync/swaync.css'
post_hook = 'swaync-client -rs'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.walker]
input_path = '~/.config/matugen/templates/walker.css'
output_path = '~/.config/walker/themes/matugen/colors.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'


[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kvantum]
input_path = '~/.config/matugen/templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathurarc'
output_path = '~/.config/zathura/matugen-zathurarc'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.vscode]
input_path = "~/.config/matugen/templates/hyprlunavsc.json"
output_path = "~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.obsidian]
input_path = "~/.config/matugen/templates/obsidian.css"
output_path = "~/Obsidian/Ether/.obsidian/themes/Matugen/theme.css"

[templates.neovim]
input_path = './templates/nvim.lua'
output_path = '~/.config/nvim/lua/generated.lua'
post_hook = 'pkill -SIGUSR1 nvim || true'

[templates.fastfetch]
input_path = './templates/fastfetch.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'


[templates.web]
input_path = './templates/web-colors.css'
output_path = '~/.config/web/colors.css'
