name = "Matugen Nyaa"

bg = "Reset"
fg = "#c9c5d0"

border = "Rounded"
border_color = "#48464f"
border_focused_color = "#c8bfff"

hl_bg = "#2a292f"

solid_bg = "#c8bfff"
solid_fg = "#30285f"

success = "#c8bfff"
error = "#ffb4ab"
info = "#c8bfff"
warning = "#ecb8ce"
