# : Manager [[[

[mgr]
cwd = { fg = "#dee4e4" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#7198ff", bg = "#7198ff" }
marker_cut      = { fg = "#d7e2ff", bg = "#d7e2ff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b8c6ea", bg = "#b8c6ea" }

# Count
count_copied   = { fg = "#0b1b36", bg = "#d7e2ff" }
count_cut      = { fg = "#0b1b36", bg = "#d7e2ff" }
count_selected = { fg = "#00363b", bg = "#b8c6ea" }

# Border
border_symbol = " "
border_style  = { fg = "#81d4dc" }

# : ]]]


# : Indicator [[[

[indicator]

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#81d4dc", bold = true, bg = "#0e1415" }
inactive  = { fg = "#b1cbce", bg = "#0e1415" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#81d4dc", fg = "#00363b", bold = true }
normal_alt  = { bg = "#1a2121", fg = "#dee4e4" }

# Select mode
select_main = { bg = "#b1cbce", fg = "#1c3437", bold = true }
select_alt  = { bg = "#1a2121", fg = "#dee4e4" }

# Unset mode
unset_main = { bg = "#b8c6ea", fg = "#21304c", bold = true }
unset_alt  = { bg = "#1a2121", fg = "#dee4e4" }

# : ]]]


# : Status [[[

[status]

# Permissions
perm_type  = { fg = "#afe4e9" }
perm_write = { fg = "#b0c0e8" }
perm_read  = { fg = "#ffa499" }
perm_exec  = { fg = "#99b5ff" }
perm_sep   = { fg = "#9ff0f9" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#81d4dc", bg = "#343a3b" }
progress_error  = { fg = "#ffb4ab", bg = "#343a3b" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3b" }
cand = { fg = "#81d4dc" }
rest = { fg = "#00363b" }
desc = { fg = "#dee4e4" }
separator = " â–¶ "
separator_style = { fg = "#dee4e4" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#b8c6ea" }
title_warn  = { fg = "#81d4dc" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#81d4dc" }
active = { fg = "#b8c6ea", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#81d4dc" }
value  = { fg = "#dee4e4" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#81d4dc", bg = "#00363b" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#81d4dc" }
title   = {}
hovered = { fg = "#d7e2ff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#dee4e4" }
run    = { fg = "#dee4e4" }
footer = { fg = "#1c3437", bg = "#b1cbce" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b4befe" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#f38ba8" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dee4e4" },
    { url = "*/", fg = "#81d4dc" },
]

# : ]]]
