# : Manager [[[

[mgr]
cwd = { fg = "#dee4e4" }

# Tab
tab_active = { fg = "#00363b", bg = "#81d4dc", bold = true }
tab_inactive = { fg = "#9df0f9", bg = "#002022" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7198ff", bg = "#7198ff" }
marker_cut = { fg = "#d7e2ff", bg = "#d7e2ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b8c6ea", bg = "#b8c6ea" }

# Count
count_copied = { fg = "#0b1b36", bg = "#d7e2ff" }
count_cut = { fg = "#0b1b36", bg = "#d7e2ff" }
count_selected = { fg = "#00363b", bg = "#b8c6ea" }

# Border
border_symbol = " "
border_style  = { fg = "#81d4dc" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00363b", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#81d4dc", fg = "#00363b", bold = true }
normal_alt  = { bg = "#1a2121", fg = "#dee4e4" }

# Select mode
select_main = { bg = "#b1cbce", fg = "#1c3437", bold = true }
select_alt  = { bg = "#1a2121", fg = "#dee4e4" }

# Unset mode
unset_main = { bg = "#b8c6ea", fg = "#21304c", bold = true }
unset_alt  = { bg = "#1a2121", fg = "#dee4e4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#81d4dc", bg = "#343a3b" }
progress_error = { fg = "#ffb4ab", bg = "#343a3b" }

# Permissions
permissions_t = { fg = "#59888d" }
permissions_w = { fg = "#4267c7" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3e73ff" }
permissions_s = { fg = "#0fd9ee" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#81d4dc" }
active = { fg = "#b8c6ea", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#81d4dc" }
value = { fg = "#dee4e4" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#81d4dc", bold = true, bg = "#0e1415" }
inactive = { fg = "#b1cbce", bg = "#0e1415" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#81d4dc", bg = "#00363b" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#81d4dc" }
title = {}
hovered = { fg = "#d7e2ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3b" }
cand = { fg = "#81d4dc" }
rest = { fg = "#00363b" }
desc = { fg = "#dee4e4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee4e4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee4e4" }
run = { fg = "#dee4e4" }
footer = { fg = "#1c3437", bg = "#b1cbce" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b8c6ea" }
title_warn = { fg = "#81d4dc" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#81d4dc" },

    # Media
    { mime = "{audio,video}/*", fg = "#b8c6ea" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#b1cbce" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dee4e4" },
    { url = "*/", fg = "#81d4dc" },
]

# : ]]]
