# : Manager [[[

[mgr]
cwd = { fg = "#f1dfdb" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#f5be45", bg = "#f5be45" }
marker_cut      = { fg = "#fae0a6", bg = "#fae0a6" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ddc48c", bg = "#ddc48c" }

# Count
count_copied   = { fg = "#251a00", bg = "#fae0a6" }
count_cut      = { fg = "#251a00", bg = "#fae0a6" }
count_selected = { fg = "#561e15", bg = "#ddc48c" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb4a6" }

# : ]]]


# : Indicator [[[

[indicator]
# padding = { open = "‚ñà", close = "‚ñà" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb4a6", bold = true, bg = "#1a1110" }
inactive  = { fg = "#e7bdb5", bg = "#1a1110" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb4a6", fg = "#561e15", bold = true }
normal_alt  = { bg = "#271d1c", fg = "#f1dfdb" }

# Select mode
select_main = { bg = "#e7bdb5", fg = "#442a25", bold = true }
select_alt  = { bg = "#271d1c", fg = "#f1dfdb" }

# Unset mode
unset_main = { bg = "#ddc48c", fg = "#3d2e04", bold = true }
unset_alt  = { bg = "#271d1c", fg = "#f1dfdb" }

# : ]]]


# : Status [[[

[status]
# sep_left  = { open = "ü≠Å", close = "ü≠†" }
# sep_right = { open = "ü≠Å", close = "ü≠†" }

# Permissions
perm_type  = { fg = "#c25641" }
perm_write = { fg = "#a17e2f" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#f2ae15" }
perm_sep   = { fg = "#ff563b" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb4a6", bg = "#423735" }
progress_error  = { fg = "#ffb4ab", bg = "#423735" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423735" }
cand = { fg = "#ffb4a6" }
rest = { fg = "#561e15" }
desc = { fg = "#f1dfdb" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f1dfdb" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#ddc48c" }
title_warn  = { fg = "#ffb4a6" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb4a6" }
active = { fg = "#ddc48c", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb4a6" }
value  = { fg = "#f1dfdb" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb4a6", bg = "#561e15" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb4a6" }
title   = {}
hovered = { fg = "#fae0a6", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f1dfdb" }
run    = { fg = "#f1dfdb" }
footer = { fg = "#442a25", bg = "#e7bdb5" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b4befe" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#f38ba8" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#f1dfdb" },
    { url = "*/", fg = "#ffb4a6" },
]

# : ]]]
