# : Manager [[[

[mgr]
cwd = { fg = "#e3e3d8" }

# Tab
tab_active = { fg = "#243600", bg = "#b7d085", bold = true }
tab_inactive = { fg = "#d2ec9f", bg = "#131f00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6dd5c6", bg = "#6dd5c6" }
marker_cut = { fg = "#bcece5", bg = "#bcece5" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a0d0c9", bg = "#a0d0c9" }

# Count
count_copied = { fg = "#00201d", bg = "#bcece5" }
count_cut = { fg = "#00201d", bg = "#bcece5" }
count_selected = { fg = "#243600", bg = "#a0d0c9" }

# Border
border_symbol = " "
border_style  = { fg = "#b7d085" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#243600", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#b7d085", fg = "#243600", bold = true }
normal_alt  = { bg = "#1e2019", fg = "#e3e3d8" }

# Select mode
select_main = { bg = "#c1caab", fg = "#2c331d", bold = true }
select_alt  = { bg = "#1e2019", fg = "#e3e3d8" }

# Unset mode
unset_main = { bg = "#a0d0c9", fg = "#013733", bold = true }
unset_alt  = { bg = "#1e2019", fg = "#e3e3d8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b7d085", bg = "#383a32" }
progress_error = { fg = "#ffb4ab", bg = "#383a32" }

# Permissions
permissions_t = { fg = "#788755" }
permissions_w = { fg = "#479085" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#45cab7" }
permissions_s = { fg = "#93ca28" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b7d085" }
active = { fg = "#a0d0c9", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#b7d085" }
value = { fg = "#e3e3d8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#b7d085", bold = true, bg = "#12140d" }
inactive = { fg = "#c1caab", bg = "#12140d" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b7d085", bg = "#243600" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#b7d085" }
title = {}
hovered = { fg = "#bcece5", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#383a32" }
cand = { fg = "#b7d085" }
rest = { fg = "#243600" }
desc = { fg = "#e3e3d8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e3e3d8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e3e3d8" }
run = { fg = "#e3e3d8" }
footer = { fg = "#2c331d", bg = "#c1caab" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a0d0c9" }
title_warn = { fg = "#b7d085" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e3e3d8" },
    { name = "*/", fg = "#b7d085" },
]

# : ]]]
