# : Manager [[[

[mgr]
cwd = { fg = "#e0e3e8" }

# Tab
tab_active = { fg = "#003450", bg = "#97ccf9", bold = true }
tab_inactive = { fg = "#cbe6ff", bg = "#001e30" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#b576ff", bg = "#b576ff" }
marker_cut = { fg = "#ecdcff", bg = "#ecdcff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d0bfe8", bg = "#d0bfe8" }

# Count
count_copied = { fg = "#211634", bg = "#ecdcff" }
count_cut = { fg = "#211634", bg = "#ecdcff" }
count_selected = { fg = "#003450", bg = "#d0bfe8" }

# Border
border_symbol = " "
border_style  = { fg = "#97ccf9" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003450", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#97ccf9", fg = "#003450", bold = true }
normal_alt  = { bg = "#1c2024", fg = "#e0e3e8" }

# Select mode
select_main = { bg = "#b8c8d9", fg = "#22323f", bold = true }
select_alt  = { bg = "#1c2024", fg = "#e0e3e8" }

# Unset mode
unset_main = { bg = "#d0bfe8", fg = "#362b4a", bold = true }
unset_alt  = { bg = "#1c2024", fg = "#e0e3e8" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#97ccf9", bg = "#363a3e" }
progress_error = { fg = "#ffb4ab", bg = "#363a3e" }

# Permissions
permissions_t = { fg = "#567ba2" }
permissions_w = { fg = "#7d4ec0" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#9943ff" }
permissions_s = { fg = "#329cff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#97ccf9" }
active = { fg = "#d0bfe8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#97ccf9" }
value = { fg = "#e0e3e8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#97ccf9", bold = true, bg = "#101417" }
inactive = { fg = "#b8c8d9", bg = "#101417" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#97ccf9", bg = "#003450" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#97ccf9" }
title = {}
hovered = { fg = "#ecdcff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#363a3e" }
cand = { fg = "#97ccf9" }
rest = { fg = "#003450" }
desc = { fg = "#e0e3e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e0e3e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e0e3e8" }
run = { fg = "#e0e3e8" }
footer = { fg = "#22323f", bg = "#b8c8d9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d0bfe8" }
title_warn = { fg = "#97ccf9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e0e3e8" },
    { name = "*/", fg = "#97ccf9" },
]

# : ]]]
