# : Manager [[[

[mgr]
cwd = { fg = "#eee0d5" }

# Tab
tab_active = { fg = "#482a00", bg = "#f9ba72", bold = true }
tab_inactive = { fg = "#ffddba", bg = "#2b1700" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#b0d169", bg = "#b0d169" }
marker_cut = { fg = "#d9e9b7", bg = "#d9e9b7" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#bdcd9d", bg = "#bdcd9d" }

# Count
count_copied = { fg = "#141f02", bg = "#d9e9b7" }
count_cut = { fg = "#141f02", bg = "#d9e9b7" }
count_selected = { fg = "#482a00", bg = "#bdcd9d" }

# Border
border_symbol = " "
border_style  = { fg = "#f9ba72" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#482a00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#f9ba72", fg = "#482a00", bold = true }
normal_alt  = { bg = "#251e17", fg = "#eee0d5" }

# Select mode
select_main = { bg = "#e0c1a3", fg = "#3f2d17", bold = true }
select_alt  = { bg = "#251e17", fg = "#eee0d5" }

# Unset mode
unset_main = { bg = "#bdcd9d", fg = "#283412", bold = true }
unset_alt  = { bg = "#251e17", fg = "#eee0d5" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f9ba72", bg = "#403830" }
progress_error = { fg = "#ffb4ab", bg = "#403830" }

# Permissions
permissions_t = { fg = "#af743b" }
permissions_w = { fg = "#748a47" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#9bc542" }
permissions_s = { fg = "#ff9221" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f9ba72" }
active = { fg = "#bdcd9d", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#f9ba72" }
value = { fg = "#eee0d5" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#f9ba72", bold = true, bg = "#18120c" }
inactive = { fg = "#e0c1a3", bg = "#18120c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f9ba72", bg = "#482a00" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#f9ba72" }
title = {}
hovered = { fg = "#d9e9b7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#403830" }
cand = { fg = "#f9ba72" }
rest = { fg = "#482a00" }
desc = { fg = "#eee0d5" }
separator = " ‚ñ∂ "
separator_style = { fg = "#eee0d5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eee0d5" }
run = { fg = "#eee0d5" }
footer = { fg = "#3f2d17", bg = "#e0c1a3" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bdcd9d" }
title_warn = { fg = "#f9ba72" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eee0d5" },
    { name = "*/", fg = "#f9ba72" },
]

# : ]]]
