# : Manager [[[

[mgr]
cwd = { fg = "#e6e1e9" }

# Tab
tab_active = { fg = "#33275e", bg = "#cbbeff", bold = true }
tab_inactive = { fg = "#e7deff", bg = "#1d1148" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff739f", bg = "#ff739f" }
marker_cut = { fg = "#ffd9e5", bg = "#ffd9e5" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#eeb8cb", bg = "#eeb8cb" }

# Count
count_copied = { fg = "#30111f", bg = "#ffd9e5" }
count_cut = { fg = "#30111f", bg = "#ffd9e5" }
count_selected = { fg = "#33275e", bg = "#eeb8cb" }

# Border
border_symbol = " "
border_style  = { fg = "#cbbeff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#33275e", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#cbbeff", fg = "#33275e", bold = true }
normal_alt  = { bg = "#48454e", fg = "#cac4cf" }

# Select mode
select_main = { bg = "#cac3dc", fg = "#322e41", bold = true }
select_alt  = { bg = "#48454e", fg = "#cac4cf" }

# Unset mode
unset_main = { bg = "#eeb8cb", fg = "#492534", bold = true }
unset_alt  = { bg = "#48454e", fg = "#cac4cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#cbbeff", bg = "#3a383e" }
progress_error = { fg = "#ffb4ab", bg = "#3a383e" }

# Permissions
permissions_t = { fg = "#7562a4" }
permissions_w = { fg = "#d03d71" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff407c" }
permissions_s = { fg = "#7845ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#cbbeff" }
active = { fg = "#eeb8cb", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#cbbeff" }
value = { fg = "#e6e1e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#cbbeff", bold = true, bg = "#141318" }
inactive = { fg = "#cac3dc", bg = "#141318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#cbbeff", bg = "#33275e" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#cbbeff" }
title = {}
hovered = { fg = "#ffd9e5", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a383e" }
cand = { fg = "#cbbeff" }
rest = { fg = "#33275e" }
desc = { fg = "#e6e1e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e6e1e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e6e1e9" }
run = { fg = "#e6e1e9" }
footer = { fg = "#322e41", bg = "#cac3dc" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#eeb8cb" }
title_warn = { fg = "#cbbeff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e6e1e9" },
    { name = "*/", fg = "#cbbeff" },
]

# : ]]]