# : Manager [[[

[mgr]
cwd = { fg = "#f1dfda" }

# Tab
tab_active = { fg = "#561f10", bg = "#ffb5a1", bold = true }
tab_inactive = { fg = "#ffdbd1", bg = "#3a0a01" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#edc249", bg = "#edc249" }
marker_cut = { fg = "#f6e1a6", bg = "#f6e1a6" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d9c58d", bg = "#d9c58d" }

# Count
count_copied = { fg = "#231b00", bg = "#f6e1a6" }
count_cut = { fg = "#231b00", bg = "#f6e1a6" }
count_selected = { fg = "#561f10", bg = "#d9c58d" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb5a1" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#561f10", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb5a1", fg = "#561f10", bold = true }
normal_alt  = { bg = "#271d1b", fg = "#f1dfda" }

# Select mode
select_main = { bg = "#e7bdb2", fg = "#442a23", bold = true }
select_alt  = { bg = "#271d1b", fg = "#f1dfda" }

# Unset mode
unset_main = { bg = "#d9c58d", fg = "#3b2f05", bold = true }
unset_alt  = { bg = "#271d1b", fg = "#f1dfda" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb5a1", bg = "#423734" }
progress_error = { fg = "#ffb4ab", bg = "#423734" }

# Permissions
permissions_t = { fg = "#c3593d" }
permissions_w = { fg = "#9a7f33" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#e8b21b" }
permissions_s = { fg = "#ff6338" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb5a1" }
active = { fg = "#d9c58d", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb5a1" }
value = { fg = "#f1dfda" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb5a1", bold = true, bg = "#1a110f" }
inactive = { fg = "#e7bdb2", bg = "#1a110f" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb5a1", bg = "#561f10" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#ffb5a1" }
title = {}
hovered = { fg = "#f6e1a6", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423734" }
cand = { fg = "#ffb5a1" }
rest = { fg = "#561f10" }
desc = { fg = "#f1dfda" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f1dfda" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f1dfda" }
run = { fg = "#f1dfda" }
footer = { fg = "#442a23", bg = "#e7bdb2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d9c58d" }
title_warn = { fg = "#ffb5a1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f1dfda" },
    { name = "*/", fg = "#ffb5a1" },
]

# : ]]]
