# : Manager [[[

[mgr]
cwd = { fg = "#e3e2e9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff70e7", bg = "#ff70e7" }
marker_cut      = { fg = "#ffd6f8", bg = "#ffd6f8" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e2bbdb", bg = "#e2bbdb" }

# Count
count_copied   = { fg = "#2b122b", bg = "#ffd6f8" }
count_cut      = { fg = "#2b122b", bg = "#ffd6f8" }
count_selected = { fg = "#1b2d60", bg = "#e2bbdb" }

# Border
border_symbol = " "
border_style  = { fg = "#b4c5ff" }

# : ]]]


# : Indicator [[[

[indicator]

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#b4c5ff", bold = true, bg = "#121318" }
inactive  = { fg = "#c1c5dd", bg = "#121318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#b4c5ff", fg = "#1b2d60", bold = true }
normal_alt  = { bg = "#1e1f25", fg = "#e3e2e9" }

# Select mode
select_main = { bg = "#c1c5dd", fg = "#2b3042", bold = true }
select_alt  = { bg = "#1e1f25", fg = "#e3e2e9" }

# Unset mode
unset_main = { bg = "#e2bbdb", fg = "#422740", bold = true }
unset_alt  = { bg = "#1e1f25", fg = "#e3e2e9" }

# : ]]]


# : Status [[[

[status]

# Permissions
perm_type  = { fg = "#99b0ff" }
perm_write = { fg = "#e1b7d9" }
perm_read  = { fg = "#ffa499" }
perm_exec  = { fg = "#ff99ee" }
perm_sep   = { fg = "#99aaff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#b4c5ff", bg = "#38393f" }
progress_error  = { fg = "#ffb4ab", bg = "#38393f" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#38393f" }
cand = { fg = "#b4c5ff" }
rest = { fg = "#1b2d60" }
desc = { fg = "#e3e2e9" }
separator = " â–¶ "
separator_style = { fg = "#e3e2e9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#e2bbdb" }
title_warn  = { fg = "#b4c5ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#b4c5ff" }
active = { fg = "#e2bbdb", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#b4c5ff" }
value  = { fg = "#e3e2e9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#b4c5ff", bg = "#1b2d60" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#b4c5ff" }
title   = {}
hovered = { fg = "#ffd6f8", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e3e2e9" }
run    = { fg = "#e3e2e9" }
footer = { fg = "#2b3042", bg = "#c1c5dd" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b4befe" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#f38ba8" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e3e2e9" },
    { url = "*/", fg = "#b4c5ff" },
]

# : ]]]
