# : Manager [[[

[mgr]
cwd = { fg = "#dee3e6" }

# Tab
tab_active = { fg = "#003543", bg = "#87d1eb", bold = true }
tab_inactive = { fg = "#b5ebff", bg = "#001f28" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7a7aff", bg = "#7a7aff" }
marker_cut = { fg = "#e0e0ff", bg = "#e0e0ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c2c3eb", bg = "#c2c3eb" }

# Count
count_copied = { fg = "#161937", bg = "#e0e0ff" }
count_cut = { fg = "#161937", bg = "#e0e0ff" }
count_selected = { fg = "#003543", bg = "#c2c3eb" }

# Border
border_symbol = " "
border_style  = { fg = "#87d1eb" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003543", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#87d1eb", fg = "#003543", bold = true }
normal_alt  = { bg = "#1b2023", fg = "#dee3e6" }

# Select mode
select_main = { bg = "#b3cad4", fg = "#1e333b", bold = true }
select_alt  = { bg = "#1b2023", fg = "#dee3e6" }

# Unset mode
unset_main = { bg = "#c2c3eb", fg = "#2b2e4d", bold = true }
unset_alt  = { bg = "#1b2023", fg = "#dee3e6" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#87d1eb", bg = "#353a3c" }
progress_error = { fg = "#ffb4ab", bg = "#353a3c" }

# Permissions
permissions_t = { fg = "#568498" }
permissions_w = { fg = "#4f52c5" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#4747ff" }
permissions_s = { fg = "#1cc2ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#87d1eb" }
active = { fg = "#c2c3eb", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#87d1eb" }
value = { fg = "#dee3e6" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#87d1eb", bold = true, bg = "#0f1416" }
inactive = { fg = "#b3cad4", bg = "#0f1416" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#87d1eb", bg = "#003543" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#87d1eb" }
title = {}
hovered = { fg = "#e0e0ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353a3c" }
cand = { fg = "#87d1eb" }
rest = { fg = "#003543" }
desc = { fg = "#dee3e6" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee3e6" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee3e6" }
run = { fg = "#dee3e6" }
footer = { fg = "#1e333b", bg = "#b3cad4" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c2c3eb" }
title_warn = { fg = "#87d1eb" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee3e6" },
    { name = "*/", fg = "#87d1eb" },
]

# : ]]]
