# : Manager [[[

[mgr]
cwd = { fg = "#dde4e2" }

# Tab
tab_active = { fg = "#003735", bg = "#80d5d1", bold = true }
tab_inactive = { fg = "#9cf1ed", bg = "#00201f" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6ba8ff", bg = "#6ba8ff" }
marker_cut = { fg = "#d1e4ff", bg = "#d1e4ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b1c8e8", bg = "#b1c8e8" }

# Count
count_copied = { fg = "#021d35", bg = "#d1e4ff" }
count_cut = { fg = "#021d35", bg = "#d1e4ff" }
count_selected = { fg = "#003735", bg = "#b1c8e8" }

# Border
border_symbol = " "
border_style  = { fg = "#80d5d1" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003735", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#80d5d1", fg = "#003735", bold = true }
normal_alt  = { bg = "#1a2120", fg = "#dde4e2" }

# Select mode
select_main = { bg = "#b0ccca", fg = "#1b3533", bold = true }
select_alt  = { bg = "#1a2120", fg = "#dde4e2" }

# Unset mode
unset_main = { bg = "#b1c8e8", fg = "#1a324b", bold = true }
unset_alt  = { bg = "#1a2120", fg = "#dde4e2" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#80d5d1", bg = "#343a3a" }
progress_error = { fg = "#ffb4ab", bg = "#343a3a" }

# Permissions
permissions_t = { fg = "#598a86" }
permissions_w = { fg = "#3b75c5" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#388aff" }
permissions_s = { fg = "#1ed6cd" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#80d5d1" }
active = { fg = "#b1c8e8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#80d5d1" }
value = { fg = "#dde4e2" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#80d5d1", bold = true, bg = "#0e1514" }
inactive = { fg = "#b0ccca", bg = "#0e1514" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#80d5d1", bg = "#003735" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#80d5d1" }
title = {}
hovered = { fg = "#d1e4ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3a" }
cand = { fg = "#80d5d1" }
rest = { fg = "#003735" }
desc = { fg = "#dde4e2" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dde4e2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dde4e2" }
run = { fg = "#dde4e2" }
footer = { fg = "#1b3533", bg = "#b0ccca" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b1c8e8" }
title_warn = { fg = "#80d5d1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#80d5d1" },

    # Media
    { mime = "{audio,video}/*", fg = "#b1c8e8" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#b0ccca" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dde4e2" },
    { url = "*/", fg = "#80d5d1" },
]

# : ]]]
