# : Manager [[[

[mgr]
cwd = { fg = "#e5e1e9" }

# Tab
tab_active = { fg = "#2b2a60", bg = "#c3c0ff", bold = true }
tab_inactive = { fg = "#e2dfff", bg = "#16134a" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff72b3", bg = "#ff72b3" }
marker_cut = { fg = "#ffd8ea", bg = "#ffd8ea" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#eab9d1", bg = "#eab9d1" }

# Count
count_copied = { fg = "#2f1123", bg = "#ffd8ea" }
count_cut = { fg = "#2f1123", bg = "#ffd8ea" }
count_selected = { fg = "#2b2a60", bg = "#eab9d1" }

# Border
border_symbol = " "
border_style  = { fg = "#c3c0ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#2b2a60", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#c3c0ff", fg = "#2b2a60", bold = true }
normal_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Select mode
select_main = { bg = "#c7c4dd", fg = "#2f2e42", bold = true }
select_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Unset mode
unset_main = { bg = "#eab9d1", fg = "#472639", bold = true }
unset_alt  = { bg = "#47464f", fg = "#c8c5d0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#c3c0ff", bg = "#39383f" }
progress_error = { fg = "#ffb4ab", bg = "#39383f" }

# Permissions
permissions_t = { fg = "#6b63a5" }
permissions_w = { fg = "#c74384" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3f98" }
permissions_s = { fg = "#5746ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#c3c0ff" }
active = { fg = "#eab9d1", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#c3c0ff" }
value = { fg = "#e5e1e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#c3c0ff", bold = true, bg = "#131318" }
inactive = { fg = "#c7c4dd", bg = "#131318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#c3c0ff", bg = "#2b2a60" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#c3c0ff" }
title = {}
hovered = { fg = "#ffd8ea", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39383f" }
cand = { fg = "#c3c0ff" }
rest = { fg = "#2b2a60" }
desc = { fg = "#e5e1e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e5e1e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e5e1e9" }
run = { fg = "#e5e1e9" }
footer = { fg = "#2f2e42", bg = "#c7c4dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#eab9d1" }
title_warn = { fg = "#c3c0ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e5e1e9" },
    { name = "*/", fg = "#c3c0ff" },
]

# : ]]]