# : Manager [[[

[mgr]
cwd = { fg = "#e8e0e8" }

# Tab
tab_active = { fg = "#3d2459", bg = "#dabafa", bold = true }
tab_inactive = { fg = "#efdbff", bg = "#270d43" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff7382", bg = "#ff7382" }
marker_cut = { fg = "#ffd9dd", bg = "#ffd9dd" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f3b7bf", bg = "#f3b7bf" }

# Count
count_copied = { fg = "#321017", bg = "#ffd9dd" }
count_cut = { fg = "#321017", bg = "#ffd9dd" }
count_selected = { fg = "#3d2459", bg = "#f3b7bf" }

# Border
border_symbol = " "
border_style  = { fg = "#dabafa" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#3d2459", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#dabafa", fg = "#3d2459", bold = true }
normal_alt  = { bg = "#4a454e", fg = "#ccc4cf" }

# Select mode
select_main = { bg = "#d0c1da", fg = "#362d3f", bold = true }
select_alt  = { bg = "#4a454e", fg = "#ccc4cf" }

# Unset mode
unset_main = { bg = "#f3b7bf", fg = "#4b252b", bold = true }
unset_alt  = { bg = "#4a454e", fg = "#ccc4cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#dabafa", bg = "#3c383e" }
progress_error = { fg = "#ffb4ab", bg = "#3c383e" }

# Permissions
permissions_t = { fg = "#8761a1" }
permissions_w = { fg = "#dd344a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff4054" }
permissions_s = { fg = "#ab42ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#dabafa" }
active = { fg = "#f3b7bf", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#dabafa" }
value = { fg = "#e8e0e8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#dabafa", bold = true, bg = "#151218" }
inactive = { fg = "#d0c1da", bg = "#151218" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#dabafa", bg = "#3d2459" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#dabafa" }
title = {}
hovered = { fg = "#ffd9dd", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c383e" }
cand = { fg = "#dabafa" }
rest = { fg = "#3d2459" }
desc = { fg = "#e8e0e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e8e0e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e8e0e8" }
run = { fg = "#e8e0e8" }
footer = { fg = "#362d3f", bg = "#d0c1da" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f3b7bf" }
title_warn = { fg = "#dabafa" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e8e0e8" },
    { name = "*/", fg = "#dabafa" },
]

# : ]]]