# : Manager [[[

[mgr]
cwd = { fg = "#dde4e2" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#6ba8ff", bg = "#6ba8ff" }
marker_cut      = { fg = "#d1e4ff", bg = "#d1e4ff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b1c8e8", bg = "#b1c8e8" }

# Count
count_copied   = { fg = "#021d35", bg = "#d1e4ff" }
count_cut      = { fg = "#021d35", bg = "#d1e4ff" }
count_selected = { fg = "#003735", bg = "#b1c8e8" }

# Border
border_symbol = " "
border_style  = { fg = "#80d5d1" }

# : ]]]


# : Indicator [[[

[indicator]

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#80d5d1", bold = true, bg = "#0e1514" }
inactive  = { fg = "#b0ccca", bg = "#0e1514" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#80d5d1", fg = "#003735", bold = true }
normal_alt  = { bg = "#1a2120", fg = "#dde4e2" }

# Select mode
select_main = { bg = "#b0ccca", fg = "#1b3533", bold = true }
select_alt  = { bg = "#1a2120", fg = "#dde4e2" }

# Unset mode
unset_main = { bg = "#b1c8e8", fg = "#1a324b", bold = true }
unset_alt  = { bg = "#1a2120", fg = "#dde4e2" }

# : ]]]


# : Status [[[

[status]

# Permissions
perm_type  = { fg = "#b2e6e3" }
perm_write = { fg = "#b0c7e8" }
perm_read  = { fg = "#ffa499" }
perm_exec  = { fg = "#99c3ff" }
perm_sep   = { fg = "#a6f2ef" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#80d5d1", bg = "#343a3a" }
progress_error  = { fg = "#ffb4ab", bg = "#343a3a" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3a" }
cand = { fg = "#80d5d1" }
rest = { fg = "#003735" }
desc = { fg = "#dde4e2" }
separator = " â–¶ "
separator_style = { fg = "#dde4e2" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#b1c8e8" }
title_warn  = { fg = "#80d5d1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#80d5d1" }
active = { fg = "#b1c8e8", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#80d5d1" }
value  = { fg = "#dde4e2" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#80d5d1", bg = "#003735" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#80d5d1" }
title   = {}
hovered = { fg = "#d1e4ff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#dde4e2" }
run    = { fg = "#dde4e2" }
footer = { fg = "#1b3533", bg = "#b0ccca" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b4befe" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#f38ba8" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dde4e2" },
    { url = "*/", fg = "#80d5d1" },
]

# : ]]]
