# : Manager [[[

[mgr]
cwd = { fg = "#dee4df" }

# Tab
tab_active = { fg = "#00382a", bg = "#89d6b9", bold = true }
tab_inactive = { fg = "#a5f2d4", bg = "#002117" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#5fc2fc", bg = "#5fc2fc" }
marker_cut = { fg = "#c3e8fe", bg = "#c3e8fe" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a7cce1", bg = "#a7cce1" }

# Count
count_copied = { fg = "#001e2b", bg = "#c3e8fe" }
count_cut = { fg = "#001e2b", bg = "#c3e8fe" }
count_selected = { fg = "#00382a", bg = "#a7cce1" }

# Border
border_symbol = " "
border_style  = { fg = "#89d6b9" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00382a", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#89d6b9", fg = "#00382a", bold = true }
normal_alt  = { bg = "#1b211e", fg = "#dee4df" }

# Select mode
select_main = { bg = "#b2ccc0", fg = "#1e352c", bold = true }
select_alt  = { bg = "#1b211e", fg = "#dee4df" }

# Unset mode
unset_main = { bg = "#a7cce1", fg = "#0b3445", bold = true }
unset_alt  = { bg = "#1b211e", fg = "#dee4df" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#89d6b9", bg = "#343b37" }
progress_error = { fg = "#ffb4ab", bg = "#343b37" }

# Permissions
permissions_t = { fg = "#5b8a74" }
permissions_w = { fg = "#3d88b2" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#2daefb" }
permissions_s = { fg = "#20de94" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#89d6b9" }
active = { fg = "#a7cce1", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#89d6b9" }
value = { fg = "#dee4df" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#89d6b9", bold = true, bg = "#0f1512" }
inactive = { fg = "#b2ccc0", bg = "#0f1512" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#89d6b9", bg = "#00382a" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#89d6b9" }
title = {}
hovered = { fg = "#c3e8fe", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343b37" }
cand = { fg = "#89d6b9" }
rest = { fg = "#00382a" }
desc = { fg = "#dee4df" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee4df" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee4df" }
run = { fg = "#dee4df" }
footer = { fg = "#1e352c", bg = "#b2ccc0" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a7cce1" }
title_warn = { fg = "#89d6b9" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee4df" },
    { name = "*/", fg = "#89d6b9" },
]

# : ]]]
