# : Manager [[[

[mgr]
cwd = { fg = "#f1dfd9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#e1c751", bg = "#e1c751" }
marker_cut      = { fg = "#f0e3a8", bg = "#f0e3a8" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d3c78f", bg = "#d3c78f" }

# Count
count_copied   = { fg = "#211c00", bg = "#f0e3a8" }
count_cut      = { fg = "#211c00", bg = "#f0e3a8" }
count_selected = { fg = "#552107", bg = "#d3c78f" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb597" }

# : ]]]


# : Indicator [[[

[indicator]
# padding = { open = "‚ñà", close = "‚ñà" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb597", bold = true, bg = "#1a110e" }
inactive  = { fg = "#e7beae", bg = "#1a110e" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb597", fg = "#552107", bold = true }
normal_alt  = { bg = "#271e1a", fg = "#f1dfd9" }

# Select mode
select_main = { bg = "#e7beae", fg = "#442a1f", bold = true }
select_alt  = { bg = "#271e1a", fg = "#f1dfd9" }

# Unset mode
unset_main = { bg = "#d3c78f", fg = "#373106", bold = true }
unset_alt  = { bg = "#271e1a", fg = "#f1dfd9" }

# : ]]]


# : Status [[[

[status]
# sep_left  = { open = "ü≠Å", close = "ü≠†" }
# sep_right = { open = "ü≠Å", close = "ü≠†" }

# Permissions
perm_type  = { fg = "#c2603a" }
perm_write = { fg = "#908139" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#dab926" }
perm_sep   = { fg = "#ff6d34" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb597", bg = "#423733" }
progress_error  = { fg = "#ffb4ab", bg = "#423733" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423733" }
cand = { fg = "#ffb597" }
rest = { fg = "#552107" }
desc = { fg = "#f1dfd9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f1dfd9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#d3c78f" }
title_warn  = { fg = "#ffb597" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb597" }
active = { fg = "#d3c78f", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb597" }
value  = { fg = "#f1dfd9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb597", bg = "#552107" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb597" }
title   = {}
hovered = { fg = "#f0e3a8", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f1dfd9" }
run    = { fg = "#f1dfd9" }
footer = { fg = "#442a1f", bg = "#e7beae" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b4befe" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#f38ba8" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#f1dfd9" },
    { url = "*/", fg = "#ffb597" },
]

# : ]]]
