# : Manager [[[

[mgr]
cwd = { fg = "#efdfe2" }

# Tab
tab_active = { fg = "#541d33", bg = "#ffb0ca", bold = true }
tab_inactive = { fg = "#ffd9e3", bg = "#3a071e" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffa15c", bg = "#ffa15c" }
marker_cut = { fg = "#ffdcc2", bg = "#ffdcc2" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#efbc94", bg = "#efbc94" }

# Count
count_copied = { fg = "#2e1500", bg = "#ffdcc2" }
count_cut = { fg = "#2e1500", bg = "#ffdcc2" }
count_selected = { fg = "#541d33", bg = "#efbc94" }

# Border
border_symbol = " "
border_style  = { fg = "#ffb0ca" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#541d33", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb0ca", fg = "#541d33", bold = true }
normal_alt  = { bg = "#261d20", fg = "#efdfe2" }

# Select mode
select_main = { bg = "#e2bdc7", fg = "#422931", bold = true }
select_alt  = { bg = "#261d20", fg = "#efdfe2" }

# Unset mode
unset_main = { bg = "#efbc94", fg = "#48290c", bold = true }
unset_alt  = { bg = "#261d20", fg = "#efdfe2" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb0ca", bg = "#403739" }
progress_error = { fg = "#ffb4ab", bg = "#403739" }

# Permissions
permissions_t = { fg = "#b3536d" }
permissions_w = { fg = "#cc6b1e" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff8429" }
permissions_s = { fg = "#ff4072" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb0ca" }
active = { fg = "#efbc94", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb0ca" }
value = { fg = "#efdfe2" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#ffb0ca", bold = true, bg = "#191114" }
inactive = { fg = "#e2bdc7", bg = "#191114" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb0ca", bg = "#541d33" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#ffb0ca" }
title = {}
hovered = { fg = "#ffdcc2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#403739" }
cand = { fg = "#ffb0ca" }
rest = { fg = "#541d33" }
desc = { fg = "#efdfe2" }
separator = " ‚ñ∂ "
separator_style = { fg = "#efdfe2" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#efdfe2" }
run = { fg = "#efdfe2" }
footer = { fg = "#422931", bg = "#e2bdc7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#efbc94" }
title_warn = { fg = "#ffb0ca" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#ffb0ca" },

    # Media
    { mime = "{audio,video}/*", fg = "#efbc94" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#e2bdc7" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#efdfe2" },
    { url = "*/", fg = "#ffb0ca" },
]

# : ]]]
