# : Manager [[[

[mgr]
cwd = { fg = "#e4e1e9" }

# Tab
tab_active = { fg = "#272b60", bg = "#bec2ff", bold = true }
tab_inactive = { fg = "#e0e0ff", bg = "#10144b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff72c2", bg = "#ff72c2" }
marker_cut = { fg = "#ffd8ee", bg = "#ffd8ee" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e8b9d5", bg = "#e8b9d5" }

# Count
count_copied = { fg = "#2e1126", bg = "#ffd8ee" }
count_cut = { fg = "#2e1126", bg = "#ffd8ee" }
count_selected = { fg = "#272b60", bg = "#e8b9d5" }

# Border
border_symbol = " "
border_style  = { fg = "#bec2ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#272b60", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#bec2ff", fg = "#272b60", bold = true }
normal_alt  = { bg = "#1f1f25", fg = "#e4e1e9" }

# Select mode
select_main = { bg = "#c5c4dd", fg = "#2e2f42", bold = true }
select_alt  = { bg = "#1f1f25", fg = "#e4e1e9" }

# Unset mode
unset_main = { bg = "#e8b9d5", fg = "#46263b", bold = true }
unset_alt  = { bg = "#1f1f25", fg = "#e4e1e9" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#bec2ff", bg = "#39393f" }
progress_error = { fg = "#ffb4ab", bg = "#39393f" }

# Permissions
permissions_t = { fg = "#6663a5" }
permissions_w = { fg = "#c24690" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3fab" }
permissions_s = { fg = "#4747ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#bec2ff" }
active = { fg = "#e8b9d5", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#bec2ff" }
value = { fg = "#e4e1e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#bec2ff", bold = true, bg = "#131318" }
inactive = { fg = "#c5c4dd", bg = "#131318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#bec2ff", bg = "#272b60" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#bec2ff" }
title = {}
hovered = { fg = "#ffd8ee", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39393f" }
cand = { fg = "#bec2ff" }
rest = { fg = "#272b60" }
desc = { fg = "#e4e1e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e4e1e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e4e1e9" }
run = { fg = "#e4e1e9" }
footer = { fg = "#2e2f42", bg = "#c5c4dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e8b9d5" }
title_warn = { fg = "#bec2ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#bec2ff" },

    # Media
    { mime = "{audio,video}/*", fg = "#e8b9d5" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#c5c4dd" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e4e1e9" },
    { url = "*/", fg = "#bec2ff" },
]

# : ]]]
