# : Manager [[[

[mgr]
cwd = { fg = "#e0e2e8" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#b976ff", bg = "#b976ff" }
marker_cut      = { fg = "#eddcff", bg = "#eddcff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d2bfe7", bg = "#d2bfe7" }

# Count
count_copied   = { fg = "#221533", bg = "#eddcff" }
count_cut      = { fg = "#221533", bg = "#eddcff" }
count_selected = { fg = "#003352", bg = "#d2bfe7" }

# Border
border_symbol = " "
border_style  = { fg = "#9acbfa" }

# : ]]]


# : Indicator [[[

[indicator]

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#9acbfa", bold = true, bg = "#101418" }
inactive  = { fg = "#b9c8da", bg = "#101418" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#9acbfa", fg = "#003352", bold = true }
normal_alt  = { bg = "#1c2024", fg = "#e0e2e8" }

# Select mode
select_main = { bg = "#b9c8da", fg = "#233240", bold = true }
select_alt  = { bg = "#1c2024", fg = "#e0e2e8" }

# Unset mode
unset_main = { bg = "#d2bfe7", fg = "#382a4a", bold = true }
unset_alt  = { bg = "#1c2024", fg = "#e0e2e8" }

# : ]]]


# : Status [[[

[status]

# Permissions
perm_type  = { fg = "#9ecdfa" }
perm_write = { fg = "#cbb5e3" }
perm_read  = { fg = "#ffa499" }
perm_exec  = { fg = "#cb99ff" }
perm_sep   = { fg = "#99caff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#9acbfa", bg = "#36393e" }
progress_error  = { fg = "#ffb4ab", bg = "#36393e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#36393e" }
cand = { fg = "#9acbfa" }
rest = { fg = "#003352" }
desc = { fg = "#e0e2e8" }
separator = " â–¶ "
separator_style = { fg = "#e0e2e8" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#d2bfe7" }
title_warn  = { fg = "#9acbfa" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#9acbfa" }
active = { fg = "#d2bfe7", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#9acbfa" }
value  = { fg = "#e0e2e8" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#9acbfa", bg = "#003352" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#9acbfa" }
title   = {}
hovered = { fg = "#eddcff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e0e2e8" }
run    = { fg = "#e0e2e8" }
footer = { fg = "#233240", bg = "#b9c8da" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#b4befe" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#fab387" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#f38ba8" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e0e2e8" },
    { url = "*/", fg = "#9acbfa" },
]

# : ]]]
