# : Manager [[[

[mgr]
cwd = { fg = "#e3e1e9" }

# Tab
tab_active = { fg = "#222c61", bg = "#bac3ff", bold = true }
tab_inactive = { fg = "#dee0ff", bg = "#0a154b" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff71cd", bg = "#ff71cd" }
marker_cut = { fg = "#ffd7f1", bg = "#ffd7f1" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e5bad8", bg = "#e5bad8" }

# Count
count_copied = { fg = "#2d1228", bg = "#ffd7f1" }
count_cut = { fg = "#2d1228", bg = "#ffd7f1" }
count_selected = { fg = "#222c61", bg = "#e5bad8" }

# Border
border_symbol = " "
border_style  = { fg = "#bac3ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#222c61", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#bac3ff", fg = "#222c61", bold = true }
normal_alt  = { bg = "#1f1f25", fg = "#e3e1e9" }

# Select mode
select_main = { bg = "#c3c5dd", fg = "#2c2f42", bold = true }
select_alt  = { bg = "#1f1f25", fg = "#e3e1e9" }

# Unset mode
unset_main = { bg = "#e5bad8", fg = "#44263e", bold = true }
unset_alt  = { bg = "#1f1f25", fg = "#e3e1e9" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#bac3ff", bg = "#39393f" }
progress_error = { fg = "#ffb4ab", bg = "#39393f" }

# Permissions
permissions_t = { fg = "#6167a6" }
permissions_w = { fg = "#bb4b99" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff3ebb" }
permissions_s = { fg = "#4550ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#bac3ff" }
active = { fg = "#e5bad8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#bac3ff" }
value = { fg = "#e3e1e9" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#bac3ff", bold = true, bg = "#121318" }
inactive = { fg = "#c3c5dd", bg = "#121318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#bac3ff", bg = "#222c61" }

# : ]]]

# : Tasks [[[

[tasks]
border = { fg = "#bac3ff" }
title = {}
hovered = { fg = "#ffd7f1", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#39393f" }
cand = { fg = "#bac3ff" }
rest = { fg = "#222c61" }
desc = { fg = "#e3e1e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e3e1e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e3e1e9" }
run = { fg = "#e3e1e9" }
footer = { fg = "#2c2f42", bg = "#c3c5dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e5bad8" }
title_warn = { fg = "#bac3ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e3e1e9" },
    { name = "*/", fg = "#bac3ff" },
]

# : ]]]
